# Cloud Build が SA 指定でも動くように
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: asia-northeast1
  _SERVICE: ai-future-diary-api

steps:
  # 1) Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/github.com/takato180/ai-future-diary:$COMMIT_SHA
      - -f
      - Dockerfile
      - .
  # 2) Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/github.com/takato180/ai-future-diary:$COMMIT_SHA

  # 3) Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - gcr.io/$PROJECT_ID/github.com/takato180/ai-future-diary:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - PROJECT_ID=$PROJECT_ID,BUCKET_NAME=ai-future-diary,VERTEX_LOCATION=us-central1,IMAGEN_MODEL=imagen-3.0-generate-001,GEMINI_MODEL=gemini-1.5-flash-002,SERVICE_ACCOUNT_EMAIL=161189042531-compute@developer.gserviceaccount.com
      - --quiet

images:
  - gcr.io/$PROJECT_ID/github.com/takato180/ai-future-diary:$COMMIT_SHA